apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-deployment
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      name: db
      labels:
        app: db-app
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db/
          env:
            - name: MONGO_INITDB_DATABASE
              value: cash-tracker
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
